---

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Tests - Node.js
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]

    steps:
      - uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@a4fcaaf314b117a40d694a35ee36461f8ff3c6e6
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install
        run: yarn install

      - name: Compile
        run: yarn build

      - name: Test
        run: yarn test

      - name: Codecov
        if: ${{ matrix.node-version == '18.x' }}
        uses: codecov/codecov-action@cc7fb3f71c712c470a895ac29f8a1fd0fcb52c8a

...
